#version 450

layout(local_size_x = 32) in;

layout(set = 0, binding = 0) buffer InputBufferA {
    float bufA[];
};

layout(set = 0, binding = 1) buffer InputBufferB {
    float bufB[];
};

layout(push_constant) uniform PushConstants {
    uint nElems;
} pcs;

void main() {
    uint idx = gl_GlobalInvocationID.x;

    if (idx >= pcs.nElems) {
        return;
    }
    bufA[idx] += bufB[idx % bufB.length()];
}