name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Build
      run: RUSTFLAGS=-Awarnings cargo build
    - name: Run tests
      run: RUSTFLAGS=-Awarnings cargo test --workspace --exclude backends::wgpu::wgpu_tensor::tests
